require("user.options")
require("user.autocmd")
require("user.packer")
require("user.theme")
require("user.treesitter")
require("user.telescope")
require("user.bufferline")
require("user.statusline")
-- require("user.startify")
require("user.lsp")
require("user.plugins")
require("user.keymap")
