#!/usr/bin/env sh

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 media_player
setup_space 2 slack
setup_space 3 chime_outlook
setup_space 4 alacritty
setup_space 5 brave

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 6
done

yabai -m rule --add app="^Friendly Streaming$" space=1
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Amazon Chime$" space=3
yabai -m rule --add app="Outlook" space=3
yabai -m rule --add app="Alacritty" space=4
yabai -m rule --add app="Brave Browser" space=5


yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config focus_follows_mouse autofocus
yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     10

yabai -m config window_border on
yabai -m config active_window_border_topmost on
yabai -m config window_border_width 2
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xF0F0FFF0
yabai -m config split_ratio 0.50
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.97
yabai -m config window_shadow off

yabai -m rule --add app="^System Settings$" title='^$' manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Digital Colour Meter" manage=off
yabai -m rule --add app="Rectangle Pro Preferences" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off

echo "yabai configuration loaded.." 
