#!/usr/bin/env sh

# yabai template colours
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 media_player
setup_space 2 communicator
setup_space 3 terminal_work
setup_space 4 browser

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 5
done

yabai -m rule --add app="^Friendly Streaming$" space=1 manage=off sticky=on
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^Amazon Chime$" space=2 manage=off
yabai -m rule --add app="Outlook" space=2
yabai -m rule --add app="Alacritty" space=3
yabai -m rule --add app="Vivaldi" space=4

yabai -m rule --add app="^System Settings$" title='^$' space=1 manage=off
yabai -m rule --add app="^Calculator$" space=1  manage=off
yabai -m rule --add app="Finder" space=1  manage=off
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on manage=off
yabai -m rule --add app="Rectangle Pro Preferences" space=1  manage=off
yabai -m rule --add app="^Karabiner-Elements$" space=1  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" space=1  manage=off
yabai -m rule --add app="^Excel$" space=1  manage=on
yabai -m rule --add app="^AmazonConnections$" space=1  manage=off

yabai -m config layout bsp
yabai -m config window_placement second_child
yabai -m config split_ratio 0.66
yabai -m config auto_balance on
yabai -m config active_window_border_topmost on
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config window_border_radius 0
yabai -m config active_window_border_color 0xF0F0FFF0
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_shadow off
yabai -m config top_padding    10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     15

yabai -m config focus_follows_mouse off
