#!/usr/bin/env sh

# change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

# change focus between external displays (left and right)
shift + alt - h: yabai -m display --focus west
shift + alt - l: yabai -m display --focus east

# rotate layout clockwise
ctrl + shift - r : yabai -m space --rotate 270

# balance
ctrl + shift - b : yabai -m space --balance

# flip along y-axis
ctrl + shift - y : yabai -m space --mirror y-axis

# flip along x-axis
ctrl + shift - x : yabai -m space --mirror x-axis

# toggle window float
ctrl + shift - t : yabai -m window --toggle float;\
					yabai -m window --grid 4:4:1:1:2:2

# swap windows
ctrl + shift - j : yabai -m window --swap south
ctrl + shift - k : yabai -m window --swap north
ctrl + shift - h : yabai -m window --swap west
ctrl + shift - l : yabai -m window --swap east

# increase window size
ctrl + cmd - l : yabai -m window --resize left:-80:0
ctrl + cmd - j : yabai -m window --resize bottom:0:80
ctrl + cmd - k : yabai -m window --resize top:0:-80
ctrl + cmd - h : yabai -m window --resize right:80:0

# decrease window size
shift + cmd - h : yabai -m window --resize left:80:0
shift + cmd - j : yabai -m window --resize bottom:0:-80
shift + cmd - k : yabai -m window --resize top:0:80
shift + cmd - l : yabai -m window --resize right:-80:0

# move window to prev and next space
ctrl + alt + cmd - p : yabai -m window --space prev
ctrl + alt + cmd - n : yabai -m window --space next

# move window to space
ctrl + alt + cmd - 1 : yabai -m window --space 1
ctrl + alt + cmd - 2 : yabai -m window --space 2
ctrl + alt + cmd - 3 : yabai -m window --space 3
ctrl + alt + cmd - 4 : yabai -m window --space 4
ctrl + alt + cmd - 5 : yabai -m window --space 5

# Restart Yabai and SKHD
hyper - r : brew services restart skhd && brew services restart yabai
